### ISSUE TITLE
Code Clarification

### ISSUE THREAD

**Issue by Mannuel25** [dark-coder-cat/empty-folder-cleaner#3]
![WhatsApp Image 2021-10-03 at 20 49 46](https://user-images.githubusercontent.com/68563757/135769513-f99b332f-d352-4b87-86af-e293f0b494e0.jpeg)

I'm a little bit confused about the codes, why does it show **[0;38;48m, [3;37;40m, [1;37;40m**?. I feel it's sort of distracting, or is it a must it's printed out?

**Comment by dark-coder-cat** [comment]
It is used for change to change the colour of the text in terminal. It should have changed the colour. Try running in Cmd/powershell directly in the terminal.

**Comment by Mannuel25** [comment]
> It is used for change to change the colour of the text in terminal. It should have changed the colour. Try running in Cmd/powershell directly in the terminal.

Okay, I'll try that now. Thanks :smile:

**Comment by dark-coder-cat** [comment]
> > It is used for change to change the colour of the text in terminal. It should have changed the colour. Try running in Cmd/powershell directly in the terminal.
> 
> Okay, I'll try that now. Thanks :smile: 

Do update me. I'll still fix it soon

**Comment by Mannuel25** [comment]
![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)

Still the same thing

**Comment by dark-coder-cat** [comment]
Sed🥲 will fix it maybe tomorrow.

**Comment by Mannuel25** [comment]
> Sedsmiling_face_with_tear will fix it maybe tomorrow.

Okay, no issues. 
I'd like to add a few things to the repo, like Contribution guidelines, Code Of Conduct, and make a few changes to the README. Kindly assign this to me

**Comment by dark-coder-cat** [comment]
> > Sedsmiling_face_with_tear will fix it maybe tomorrow.
> 
> Okay, no issues. 
> I'd like to add a few things to the repo, like Contribution guidelines, Code Of Conduct, and make a few changes to the README. Kindly assign this to me

For sure☺️

**Comment by dark-coder-cat** [comment]
> ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> 
> Still the same thing. Does it work well on your PC?

- Added a fix for this in latest commit. 
- And sorry i didn't read the question. Yeah i works for me.

**Comment by Mannuel25** [comment]
> > ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> > Still the same thing. Does it work well on your PC?
> 
> * Added a fix for this in latest commit.
> * And sorry i didn't read the question. Yeah i works for me.

Okay, I'll give it another shot on my PC.

**Comment by Mannuel25** [comment]
> > > ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> > > Still the same thing. Does it work well on your PC?
> > 
> > 
> > 
> > * Added a fix for this in latest commit.
> > * And sorry i didn't read the question. Yeah i works for me.
> 
> Okay, I'll give it another shot on my PC.

Still the same thing

**Comment by dark-coder-cat** [comment]
> > > > ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> > > > Still the same thing. Does it work well on your PC?
> > > 
> > > 
> > > 
> > > * Added a fix for this in latest commit.
> > > * And sorry i didn't read the question. Yeah i works for me.
> > 
> > Okay, I'll give it another shot on my PC.
> 
> Still the same thing
> 

Did you try the option 3 in starting

**Comment by Mannuel25** [comment]
> > > > > ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> > > > > Still the same thing. Does it work well on your PC?
> > > > 
> > > > 
> > > > 
> > > > * Added a fix for this in latest commit.
> > > > * And sorry i didn't read the question. Yeah i works for me.
> > > 
> > > 
> > > Okay, I'll give it another shot on my PC.
> > 
> > 
> > Still the same thing
> 
> Did you try entering the option 3 in starting?

Yes, I did. I'd the same results.

**Comment by dark-coder-cat** [comment]
> > > > > > ![WhatsApp Image 2021-10-03 at 21 07 39](https://user-images.githubusercontent.com/68563757/135769848-71dff0ff-1a9f-4408-8aa7-67a4b87334b8.jpeg)
> > > > > > Still the same thing. Does it work well on your PC?
> > > > > 
> > > > > 
> > > > > 
> > > > > * Added a fix for this in latest commit.
> > > > > * And sorry i didn't read the question. Yeah i works for me.
> > > > 
> > > > 
> > > > Okay, I'll give it another shot on my PC.
> > > 
> > > 
> > > Still the same thing
> > 
> > Did you try entering the option 3 in starting?
> 
> Yes, I did. I'd the same results.

😳How come it's working for me

**Comment by Mannuel25** [comment]
Wow, I'll try running it on Pydroid. Let's see the outcome

**Comment by Mannuel25** [comment]
> Wow, I'll try running it on Pydroid. Let's see the outcome

I tried it, didn't get the [0:38.. , worked fine. But it says 0 total folders scanned, 0 total file and folder

**Comment by dark-coder-cat** [comment]
> > Wow, I'll try running it on Pydroid. Let's see the outcome
> 
> I tried it, didn't get the [0:38.. , worked fine. But it says 0 total folders scanned, 0 total file and folder

Which folder did you scan?

**Comment by Mannuel25** [comment]
> > > Wow, I'll try running it on Pydroid. Let's see the outcome
> > 
> > 
> > I tried it, didn't get the [0:38.. , worked fine. But it says 0 total folders scanned, 0 total file and folder
> 
> Which folder did you scan?

Oh, I picked 1 I guess..trying again

**Comment by Mannuel25** [comment]
> > > > Wow, I'll try running it on Pydroid. Let's see the outcome
> > > 
> > > 
> > > I tried it, didn't get the [0:38.. , worked fine. But it says 0 total folders scanned, 0 total file and folder
> > 
> > 
> > Which folder did you scan?
> 
> Oh, I picked 1 I guess..trying again

Just did that, worked perfectly!. It's cool  :smile:

**Comment by Mannuel25** [comment]
But doesn't it display well on my PC? :rofl:

**Comment by dark-coder-cat** [comment]
> But why doesn't it display well on my PC? :rofl: 

😂 It should work after entering 3.

**Comment by Mannuel25** [comment]
> > But why doesn't it display well on my PC? rofl
> 
> joy It should work after entering 3.

Yes it did!

**Comment by Mannuel25** [comment]
This is a good tool :clap:

**Comment by dark-coder-cat** [comment]
> This is a good tool :clap: 

Thnx😀

**Comment by Mannuel25** [comment]
I forgot to mention that the colors didn't change, it worked well. But the color was white all through asides when it displayed '...Removed..' this changed to red

**Comment by Mannuel25** [comment]
![IMG_20211004_174911_910](https://user-images.githubusercontent.com/68563757/135892251-e380b8ee-718a-4b95-886b-7da4dd1b90f5.jpg)

I got this output

**Comment by Mannuel25** [comment]
Also, what does option 3 do? Does it make the colors active or what?

**Comment by dark-coder-cat** [comment]
> I forgot to mention that the color did not change and that it worked perfectly..the color was white throughout. But when it displayed '...Removed..' it changed to red.

Yeah this is the only color i had set (atleast for now) the nos. And some sentences Are set to bright for those whose terminal default isn't white would only be able to notice

**Comment by dark-coder-cat** [comment]
> Also, what does option 3 do? Does it make the colors active or what?

It changes all color variable strings to emptry string so it would be like printing normally. In other words it removed the modifying of colours.

**Comment by Mannuel25** [comment]
Oh, got that. Thanks for the clarifications!
